Account_no=int(input("Enter your account no:"))
Full_name=input("Enter your Full name:")
Occupation=input("Enter your Occupation:")
Adress=input("Enter Adress:")
Ifsc_code=input("Enter IFSC:")
Branch_name=input("Enter branch name:")
Contact_no =int(input("Enter contact no:"))
Email_id =input("Enter emailid:")
print("________________________________________________________________________________________________________")
print("************************You are  details registered successfully********************************************")