Student_id=int(input("Enter your id:"))
Username=input("Enter your username:")
Clas=input("Enter class:")
Branch=input("Enter branch:")
Gender =input("Enter gender:")
Age =int(input("Enter age:"))
Contact =int(input("Enter contact no:"))
Emailid =input("Enter emailid:")
print("________________________________________________________________________________________________________")
print("****************************You are registered successfully******************************************")